### PR TITLE
[test] Port DGEMM check to Tiger

### PR DESCRIPTION
**Pull request by jgphpc**
Will fix UES-567

### CODE REVIEW

**Comment by jgphpc** [comment]
```
[     FAIL ] DGEMMTest on dom:mc using PrgEnv-gnu
[     FAIL ] DGEMMTest on dom:gpu using PrgEnv-gnu
```

```
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for DGEMMTest 
  * System partition: dom:gpu
  * Environment: PrgEnv-gnu
  * Stage directory: /scratch/snx3000tds/jenscscs/reframe-ci-dom-754e540-2559/stage/dom/gpu/PrgEnv-gnu/DGEMMTest
  * Job type: batch job (id=806463)
  * Maintainers: ['AJ', 'VH', 'VK']
  * Failing phase: performance
  * Reason: performance error: failed to meet reference: nid00002=193.31553, expected 300.0 (l=255.0, u=inf)
------------------------------------------------------------------------------
FAILURE INFO for DGEMMTest 
  * System partition: dom:mc
  * Environment: PrgEnv-gnu
  * Stage directory: /scratch/snx3000tds/jenscscs/reframe-ci-dom-754e540-2559/stage/dom/mc/PrgEnv-gnu/DGEMMTest
  * Job type: batch job (id=806465)
  * Maintainers: ['AJ', 'VH', 'VK']
  * Failing phase: performance
  * Reason: performance error: failed to meet reference: nid00406=497.16049, expected 860.0 (l=731.0, u=inf)
```

**Comment by jgphpc** [comment]
@jenkins-cscs retry none

**Comment by jgphpc** [comment]
@jenkins-cscs retry dom

**Comment by jgphpc** [comment]
@jenkins-cscs retry dom

**Comment by jgphpc** [comment]
```

**Comment by vkarak** [comment]
For the failure on Dom, refer to MAINT-178. Merging.

**Pull request merged**
