### PR TITLE
[feat] Remove runtime timings from the default output

### LINKED ISSUE #2415: test runtime statistics with incorrect run and total values
Using ReFrame 3.10.0, the timing stats look off. this is a set of tests that gets executed sequentially (there is only 1 node, using it exclusively). The run and total stats per test look like total offset from when reframe was launched. I expected the test (job) runtime (roughly),  and total = compile+run.
See also the perf report below, that shows the actual test runtimes, 1,5 - 5 minutes

```
[----------] start processing checks
[ RUN      ] VASPCpuCheck %tasks=88 %node_type=m1 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=76 %node_type=m2 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=76 %node_type=m1 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=64 %node_type=m2 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=64 %node_type=m1 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=32 %node_type=m2 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=32 %node_type=m1 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=16 %node_type=m2 @cbe:mem+intelmpi2019b
[ RUN      ] VASPCpuCheck %tasks=16 %node_type=m1 @cbe:mem+intelmpi2019b
[       OK ] (1/9) VASPCpuCheck %tasks=88 %node_type=m1 @cbe:mem+intelmpi2019b [compile: 0.013s run: 172.772s total: 173.114s]
[       OK ] (2/9) VASPCpuCheck %tasks=76 %node_type=m1 @cbe:mem+intelmpi2019b [compile: 0.015s run: 293.105s total: 295.378s]
[       OK ] (3/9) VASPCpuCheck %tasks=64 %node_type=m1 @cbe:mem+intelmpi2019b [compile: 0.015s run: 423.151s total: 427.416s]
[       OK ] (4/9) VASPCpuCheck %tasks=32 %node_type=m1 @cbe:mem+intelmpi2019b [compile: 0.015s run: 593.286s total: 599.524s]
[       OK ] (5/9) VASPCpuCheck %tasks=16 %node_type=m1 @cbe:mem+intelmpi2019b [compile: 0.014s run: 934.704s total: 942.955s]
^C[     FAIL ] (6/9) VASPCpuCheck %tasks=76 %node_type=m2 @cbe:mem+intelmpi2019b [compile: 0.014s run: 1072.532s total: 1073.872s]
==> test failed during 'run': test staged in '/users/adm_ebirn/projects/clip-reframe-dev/stage/2022-02-02T23_36/cbe/mem/intelmpi2019b/VASPCpuCheck_76_m2'
[     FAIL ] (7/9) VASPCpuCheck %tasks=64 %node_type=m2 @cbe:mem+intelmpi2019b [compile: 0.015s run: 1070.522s total: 1073.807s]
==> test failed during 'run': test staged in '/users/adm_ebirn/projects/clip-reframe-dev/stage/2022-02-02T23_36/cbe/mem/intelmpi2019b/VASPCpuCheck_64_m2'
[     FAIL ] (8/9) VASPCpuCheck %tasks=32 %node_type=m2 @cbe:mem+intelmpi2019b [compile: 0.016s run: 1068.480s total: 1073.738s]
==> test failed during 'run': test staged in '/users/adm_ebirn/projects/clip-reframe-dev/stage/2022-02-02T23_36/cbe/mem/intelmpi2019b/VASPCpuCheck_32_m2'
[     FAIL ] (9/9) VASPCpuCheck %tasks=16 %node_type=m2 @cbe:mem+intelmpi2019b [compile: 0.016s run: 1066.398s total: 1073.671s]
==> test failed during 'run': test staged in '/users/adm_ebirn/projects/clip-reframe-dev/stage/2022-02-02T23_36/cbe/mem/intelmpi2019b/VASPCpuCheck_16_m2'
[  FAILED  ] Ran 5/9 test case(s) from 9 check(s) (0 failure(s), 0 skipped)
[==========] Finished on Wed Feb  2 23:54:11 2022 

==============================================================================
PERFORMANCE REPORT
------------------------------------------------------------------------------
VASPCpuCheck %tasks=88 %node_type=m1
- cbe:mem
   - intelmpi2019b
      * num_tasks: 88
      * time: 88.653 s
------------------------------------------------------------------------------
VASPCpuCheck %tasks=76 %node_type=m1
   - intelmpi2019b
      * num_tasks: 76
      * time: 91.34 s
------------------------------------------------------------------------------
VASPCpuCheck %tasks=64 %node_type=m1
   - intelmpi2019b
      * num_tasks: 64
      * time: 104.521 s
------------------------------------------------------------------------------
VASPCpuCheck %tasks=32 %node_type=m1
   - intelmpi2019b
      * num_tasks: 32
      * time: 155.553 s
------------------------------------------------------------------------------
VASPCpuCheck %tasks=16 %node_type=m1
   - intelmpi2019b
      * num_tasks: 16
      * time: 261.269 s
```

### PR DESCRIPTION
**Pull request by ekouts**
It might be better to remove the runtime timings from the default output, after the conversation in #2415 . 
The documentation mentions that these timings correspond only to the ReFrame stages, but it can be misleading for new users that want to use them for performance monitoring.
Normal output:
```
[----------] start processing checks
[ RUN      ] T0 @generic:default+builtin
[       OK ] ( 1/10) T0 @generic:default+builtin
[ RUN      ] T4 @generic:default+builtin
[       OK ] ( 2/10) T4 @generic:default+builtin
```
Verbose output:
```
[----------] start processing checks
[ RUN      ] T0 @generic:default+builtin
[       OK ] ( 1/10) T0 @generic:default+builtin
==> setup: 0.019s compile: 0.035s run: 0.476s sanity: 0.000s performance: 0.000s total: 0.568s
[ RUN      ] T4 @generic:default+builtin
[       OK ] ( 2/10) T4 @generic:default+builtin
==> setup: 0.009s compile: 0.036s run: 0.375s sanity: 0.000s performance: 0.000s total: 0.459s
```
I still leave them in verbose mode, what do you think @vkarak ? If you agree I will change also all the reframe outputs in the docs.

Closes #2415.

### CODE REVIEW

**Comment by vkarak** [comment]
Should we also close #2415 with this?

**Comment by ekouts** [comment]
I think so, yes.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Review by vkarak — COMMENTED** [review]
Lgtm, I have a minor comment for improvement.

**Review by vkarak — APPROVED** [review]

**Pull request merged**
