### PR TITLE
[test] Add Jupyter tests for Eiger

### PR DESCRIPTION
**Pull request by rsarm**
Closes UES-1679

The `ipcmagic` test is not ported as it requires TensorFlow.

### CODE REVIEW

**Review by lucamar — COMMENTED** [review]
Thanks @rsarm: is it also possible to target the system Pilatus?

**Comment by rsarm** [comment]
I don't think so. There are currently no reservations on Pilatus for jupyter.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by lucamar** [comment]
We might get Jupyter running on PIlatus soon: see [SD-52889](https://jira.cscs.ch/projects/SD/queues/custom/48/SD-52889)

**Review by vkarak — APPROVED** [review]

**Comment by vkarak** [comment]
@jenkins-cscs retry eiger pilatus

**Pull request merged**
