### PR TITLE
ddt_check_Cuda fails after maintenance

### PR DESCRIPTION
**Pull request by jgphpc**
fix for #328

### CODE REVIEW

**Comment by teojgo** [comment]
@jgphpc why did  you change the `notool.py` and not the `ddt.py`?

**Comment by jgphpc** [comment]
>    [1]@jgphpc why did you change the notool.py and not the ddt.py?
wrong push, vk is trying to fix it.

**Comment by vkarak** [comment]
The problem, guys, is that this has been accidentally pushed to master. And perhaps the master is broken. It won't be an easy fix.. There are merges dispersed over time...

**Comment by teojgo** [comment]
Maybe then reset to the `origin/master` and just make the change to `ddt.py`

**Comment by vkarak** [comment]
@teojgo Not so simple. At commit bfbdb3742e06e420fd0d73b2d061bf0bb35f17eb, @jgphpc has pushed into his local master some changes in the settings, so every time he was pulling, new merge commits were inserted! I don't think we can get rid of them. I will just try to check that the repo is in a sane state.

**Comment by vkarak** [comment]
I've forced pushed from my fork, which was up to date. I am closing this PR and you resubmit. 

@jgphpc Make sure to first `git reset` your master before pulling. Otherwise we will end up to the same situation.

**Pull request closed without merging**
