### PR TITLE
[feat] Add support for logging all performance variables to a single line

### LINKED ISSUE #1543: Allow multiple perf_patterns on one line in handlers_perflog
When specifying multiple entries in perf_patterns (for instance as in cscs-checks/microbenchmarks/mpi/halo_exchange/halo_cell_exchange.py), every performance variable is put on a separate line by the logging handler. All attributes that are not related to the performance variable are repeated on all those lines.

For the HaloCellExchangeTest you could argue that every performance represents a separate aspect of the test, so it makes sense to put them on separate lines. However, when you are for instance looking at walltime, CPU time, communication time, memory, ... in one test, it would make more sense to keep those performance variables tied together. At the moment, it is necessary to join lines on some common attribute (such as jobid) to find out which results belong together.

I think it would be a useful feature to allow the `%(check_perf_*)s` attributes to report multiple values, similar to the `%(check_tags)s` attribute. Before attempting to implement this, I would like the opinion of a developer on this. Or maybe there is a hack to work around this issue?

### PR DESCRIPTION
**Pull request by stevenvdb**
This PR introduces log record attributes such as `%(check_perf_all_values)s` that will be filled in with a comma-separated list of values from all entries in `perf_patterns`. When the existing log record attributes such as `%(check_perf_value)s` are omitted, this changes the existing behavior that a separate line is logged for each entry in `per_patterns`.

Closes #1543

### CODE REVIEW

**Review by vkarak — CHANGES_REQUESTED** [review]
Hi @stevenvdb, thanks for your PR. Instead of having the different `check_perf_all_*` format specifiers, I was wondering wether it would make more sense to have a single one, say `check_perf_data` that would actually print all performance variables and values at once as key value pairs. Something like this:

```
perfX=valX[unitX],perfY=valY[unitY],...
```

We could even have `check_perf_data_fmt` (similarly to `datefmt`) that would allow users to explicitly specify the perf data format that they want based on the existing `check_perf_*` values. This will allow to even log `check_perf_data` as JSON:

```python
'check_perf_data_fmt': '{"perfvar": %(check_perf_var)s, "value": %(check_perf_value)s, ...}'
```

**Comment by vkarak** [comment]
@stevenvdb After merging #1600 and #1644, we will no more need the `check_perf_all` variables you introduce here. You will now be able to use `%(check_perf_patterns)s` and this will log all the performance variables and values at once in JSON format. From this PR, we still need the part about creating a single log entry for the performance. If you are fine with I propose here, I can update the PR and schedule it for ReFrame 3.4.

**Comment by vkarak** [comment]
Also if you need a different formatting of the performance variables, you can define an arbitrary field in your test and log that always. In this case, we probably need to find another way to force logging of performance data to happen only once.

**Comment by stevenvdb** [comment]
> 
> 
> @stevenvdb After merging #1600 and #1644, we will no more need the `check_perf_all` variables you introduce here. You will now be able to use `%(check_perf_patterns)s` and this will log all the performance variables and values at once in JSON format. From this PR, we still need the part about creating a single log entry for the performance. If you are fine with I propose here, I can update the PR and schedule it for ReFrame 3.4.

I think your proposition sounds good. What do you think is the best way to trigger the single log entry on or off? You could set it based on the presence of `%(check_perf_patterns)s` or let the user specify it explicitly in the configuration file.

**Comment by vkarak** [comment]
@stevenvdb Sorry for getting back to you late. I was quite busy and then I can't figure out which is the best way to handle this :-) First of all, I think that the logic of whether to iterate or not over the performance variables should be moved inside the `log_performance()` function in `core/logging.py`. The signature of this function would need to be updated, too, so that it simply takes the evaluated `perf_patterns`. It's then the logger that will decide whether to do log each performance variable separately or not. The question is how this behaviour is controlled. Doing this automatically and having the logger inspecting its handlers for this, hmm, it may be convenient for the user, but implementation-wise breaks encapsulation and separation of concerns and I am a bit skeptical about it. Having a configuration variable that controls this, it's much cleaner from the implementation point of view, but that would require the users to remember to set this configuration parameter if they're using `%(check_perf_patterns)s` in their format string, which can be error-prone. If you have any suggestions, I'm more than happy to hear them.

**Comment by vkarak** [comment]
Hi @stevenvdb, #1816 allows you also to log all the references in a single line, so now you can have `%(check_perf_patterns)s` and `%(check_reference)s` to get everything in a single line. You will still have redundant lines, but there is no need to join them anymore. If you don't mind, I will close this PR, but keep #1543 open and schedule it for the next major release. The reason for this is that it's probably better to drop altogether the `log_performance()` function and the redundant lines, but this is a breaking change, so it should be scheduled for 4.0. Meanwhile, I think that you can use the format specifiers I just mentioned to achieve what you want. Let me know if that fits you.

**Comment by stevenvdb** [comment]
> 
> 
> Hi @stevenvdb, #1816 allows you also to log all the references in a single line, so now you can have `%(check_perf_patterns)s` and `%(check_reference)s` to get everything in a single line. You will still have redundant lines, but there is no need to join them anymore. If you don't mind, I will close this PR, but keep #1543 open and schedule it for the next major release. The reason for this is that it's probably better to drop altogether the `log_performance()` function and the redundant lines, but this is a breaking change, so it should be scheduled for 4.0. Meanwhile, I think that you can use the format specifiers I just mentioned to achieve what you want. Let me know if that fits you.

Hi @vkarak,

That sounds look a good solution to me, thanks. I will close this PR.

**Pull request closed without merging**
