### PR TITLE
[bugfix] Fix bootstrap script for Ubuntu/Debian installation

### LINKED ISSUE #1467: Boostrapping throws an ensurepip error in Ubuntu
In order to reproduce the problem, the following Dockerfile can be use:

```
FROM ubuntu

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-setuptools --no-install-recommends

RUN apt-get install -y git --no-install-recommends

RUN git clone https://github.com/eth-cscs/reframe.git && \
    cd reframe && ./bootstrap.sh
```

Trying to build the above with Docker, it will throw the error in Step 4:
```
==> python3 -m ensurepip --root external/ --default-pip
/usr/bin/python3: No module named ensurepip
==> python3 -m pip install -q --upgrade pip --target=external/
==> python3 -m pip install -q -r requirements.txt --target=external/ --upgrade
```

Nevertheless, the bootstrapping continues fine.

### PR DESCRIPTION
**Pull request by teojgo**
Fixes #1467

### CODE REVIEW

**Comment by victorusu** [comment]
`lgtm`

**Review by victorusu — APPROVED** [review]
`lgtm`

**Review by victorusu — APPROVED** [review]
`lgtm`

**Review by vkarak — CHANGES_REQUESTED** [review]
Lgtm, except that I think we should a comment in the documentation that a Python installation with pip is required, because if you get `python3-minimal` in Ubuntu (the default `python3` package), it will not work.

**Review by vkarak — APPROVED** [review]
lgtm now. I fixed the documentation.

**Pull request merged**
