### PR TITLE
[test] Adapt PrgEnv-cray flags for Trilinos check

### PR DESCRIPTION
**Pull request by ajocksch**
This PR considers the new compiler flags for the Cray compiler (clang).

The old flags still exist in PrgEnv-cray_classic.

### CODE REVIEW

**Comment by vkarak** [comment]
@ajocksch Please add a description to your PR.

**Comment by vkarak** [comment]
@ajocksch Can you be more specific in your PR title and put a description of what this PR offers? Also why is it a WIP?

**Comment by vkarak** [comment]
@jenkins-cscs retry dom

**Comment by vkarak** [comment]
Test still fails on Dom. Please fix:

```
==============================================================================
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for TrilinosTest_static
  * System partition: dom:gpu
  * Environment: PrgEnv-cray_classic
  * Stage directory: /users/karakasv/Devel/reframe/stage/dom/gpu/PrgEnv-cray_classic/TrilinosTest_static
  * Node list: <None>
  * Job type: batch job (id=None)
  * Maintainers: ['AJ', 'CB']
  * Failing phase: compile_wait
  * Reason: build error: standard error can be found in `rfm_TrilinosTest_static_build.err', standard output can be found in `rfm_TrilinosTest_static_build.out'
------------------------------------------------------------------------------
FAILURE INFO for TrilinosTest_static
  * System partition: dom:mc
  * Environment: PrgEnv-cray_classic
  * Stage directory: /users/karakasv/Devel/reframe/stage/dom/mc/PrgEnv-cray_classic/TrilinosTest_static
  * Node list: <None>
  * Job type: batch job (id=None)
  * Maintainers: ['AJ', 'CB']
  * Failing phase: compile_wait
  * Reason: build error: standard error can be found in `rfm_TrilinosTest_static_build.err', standard output can be found in `rfm_TrilinosTest_static_build.out'
------------------------------------------------------------------------------
```

**Comment by vkarak** [comment]
Also there tons of warnings for the `PrgEnv-cray`.

**Comment by ajocksch** [comment]
Cray case #257684 about trilinos not supported for cce/xxx-classic

**Comment by ajocksch** [comment]
the warnings come from the trilinos header files, I see only the option to suppress them, changes to the c++ standard version did not help

**Comment by vkarak** [comment]
@jenkins-cscs retry none

**Pull request merged**
