### PR TITLE
[feat] allow grep_command_output() to accept a list or tuple of patterns

### PR DESCRIPTION
**Pull request by smoors**

### CODE REVIEW

**Comment by vkarak** [comment]
Hi @smoors and thanks for contributing. I am wondering why would you need that? These `os_ext` utilities are only meant for internal framework use. You are not supposed to use them in your test. For `grep`-ing patterns in your test output, there are the sanity functions, which are much more powerful.

**Comment by smoors** [comment]
hi @vkarak ! thanks for your quick reply.

it's not meant for testing.
currently there is no `torque` scheduler implemented yet, so I am implementing one based on the (very rudimentary) `pbs` scheduler.
to check the status of a job it would be nice if we can search for multiple regexes in one go, avoiding unneeded querying of the scheduler.

**Comment by vkarak** [comment]
Good to know that you are working on a Torque backend! In fact, we have issue #1070 for that. I could assign it to you, if you wish. It'd be better to see the changes you propose in this PR as part of a larger PR about the Torque backend, where we could see the context better. Is this ok with you?

**Comment by smoors** [comment]
sure :)
I've got a basic version working, but want to refine it a bit.

**Comment by vkarak** [comment]
Great! I'll close this PR then and wait for your other with the full implementation. If you want to share your work in progress, you can always open a PR and mark with `[wip]` in the title.

**Pull request closed without merging**
