### PR TITLE
[feat] Extend `Job` API for retrieving the list of nodes assigned to the regression test

### LINKED ISSUE #565: Extend the `Job` API so as to provide the node list of the allocation
This feature is useful for flexible diagnostics tests. A custom sanity function could quickly identify and report the failing node(s).

### PR DESCRIPTION
**Pull request by omlins**
closes #565

### CODE REVIEW

**Comment by omlins** [comment]
closes #565

**Comment by vkarak** [comment]
@omlins The "Closes issue"  clause must be in the description in order to have an effect.

**Comment by omlins** [comment]
@jenkins-cscs retry all

**Comment by vkarak** [comment]
@teojgo @victorusu Can you please review? @victorusu, does this feature serve you correctly with the flexible tests?

**Pull request merged**
