### PR TITLE
[test] Scalapack check: remove custom code

### PR DESCRIPTION
**Pull request by ChristopherBignamini**

### CODE REVIEW

**Comment by vkarak** [comment]
@ChristopherBignamini I think you mixed up this PR with other tests.

**Comment by ChristopherBignamini** [comment]
Yes, sorry...I don't know what happened, can we delete the PR?

**Comment by ChristopherBignamini** [comment]
No need to close, it should be ok now

**Review by vkarak — CHANGES_REQUESTED** [review]
This is not enough we should remove the access to the resourcesdir altogether in the test by moving the original file in the test's `sourcesdir`.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Review by vkarak — APPROVED** [review]

**Pull request merged**
