### PR TITLE
Strip the reason details before testing for match

### LINKED ISSUE #303: 'ReqNodeNotAvail' is not always a reason of indefinite blocking of a job
In fact, on Kesch this is the reason we get when a job is just pending:

```
ReqNodeNotAvail,  UnavailableNodes:
```

I think here the key is that the `UnavailableNodes` list is empty. Perhaps, we need to have a more robust check before cancelling the job.

### PR DESCRIPTION
**Pull request by teojgo**
Closes #303

### CODE REVIEW

**Comment by teojgo** [comment]
@kraushm can you try now in kesch?

**Comment by teojgo** [comment]
@jenkins-cscs retry all

**Comment by kraushm** [comment]
First run on Kesch passed as well, will do some more runs.

**Comment by kraushm** [comment]
Further tests are ok. Job on Kesch was queued for approx. 5min with `(ReqNodeNotAvail, UnavailableNodes:)` without being killed.

**Pull request merged**
