### PR TITLE
[test] Update AllocSpeedTest and enable it for Eiger

### PR DESCRIPTION
**Pull request by toxa81**
Looks like gcc/10 has more compile-time optimizations. This is fixed now.

### CODE REVIEW

**Comment by vkarak** [comment]
ok to test

**Comment by toxa81** [comment]
@ekouts Let me know how it runs on Eiger. I tested it myself and it looks OK.

**Review by ekouts — APPROVED** [review]
Thanks @toxa81 , it looks good on eiger and the timings on dom went back to normal. :)

**Review by vkarak — APPROVED** [review]

**Comment by teojgo** [comment]
@ekouts, maybe put larger margins for lower values so that we can accept even better values but still not accept negative values.

**Comment by ekouts** [comment]
> @ekouts, maybe put larger margins for lower values so that we can accept even better values but still not accept negative values

@vkarak what do you think? Should we put larger margins? I was looking at older performance values and in general it looks stable.

**Comment by teojgo** [comment]
> > @ekouts, maybe put larger margins for lower values so that we can accept even better values but still not accept negative values
> 
> @vkarak what do you think? Should we put larger margins? I was looking at older performance values and in general it looks stable.

I suggested since I saw a failure on dom at some point where the allocation speed was even faster.

**Comment by vkarak** [comment]
@ekouts Perhaps it makes sense to make the threshold 20% on the fast side.

**Review by teojgo — APPROVED** [review]

**Pull request merged**
