### PR TITLE
[bugfix] Fix early abort when compile step fails with async policy

### LINKED ISSUE #1330: Tasks waiting to run are silently aborted if a later task fails compile stage, with async policy
This might be related to #1121 and/or #507 

When using the AsynchronousExecutionPolicy, a task failure at the compile if a tasks fails at the compile_wait step can lead to reframe exiting while earlier queued jobs are still waiting to run.

I think the root cause is in `reframe/frontend/executors/policies.py` -> `class AsynchronousExecutionPolicy(ExecutionPolicy, TaskEventListener)` ->   `def _reschedule(self, task):`, `compile_wait` can throw a variety of compile-time errors that should fail the task, but not abort the reframe run.

I have a patch that I think fixes this, will post an PR shortly

### PR DESCRIPTION
**Pull request by sleak-lbl**
Fixes #1330 

Exceptions raised from build tasks within `compile_wait` with the async policy are not caught by `reschedule_task`, and so bubble up and stop the reframe process. Any queued jobs then get abandoned.

This PR catches exceptions that should cause the test, but not the whole reframe run, to fail

### CODE REVIEW

**Comment by sleak-lbl** [comment]
I've just had an early abort with this patch in place, so it's clearly not the soltion (or at least, the full solution) .. I've added a WIP marker to the PR, digging a bit more now

**Comment by vkarak** [comment]
Check my comment in the issue for a possible cause of this bug.

**Comment by vkarak** [comment]
@sleak-lbl Can you test this PR now with a real workload?

**Comment by sleak-lbl** [comment]
tested with real workload and verified it worked (and, as far as I can tell, worked for the right reasons) - so I think it is good to go

**Comment by vkarak** [comment]
Thanks for testing and confirming @sleak-lbl !

**Pull request merged**
