### PR TITLE
[bugfix] Change to working directory before merging job array files

### LINKED ISSUE #839: ReFrame fails to detect job status of Slurm job arrays
When running a Slurm job array using `#SBATCH --array=<array_specs>`, ReFrame fails to detect the status of the job from its `sacct` polling. The logs include things like:

```
[2019-06-20T12:18:49] debug: slurm_job_arrays on cori:knl using PrgEnv-intel: entering stage: poll
[2019-06-20T12:18:49] debug: slurm_job_arrays on cori:knl using PrgEnv-intel: executing OS command: sacct -S 2019-06-20 -P -j 2242
3095 -o jobid,state,exitcode,nodelist
[2019-06-20T12:18:49] debug: slurm_job_arrays on cori:knl using PrgEnv-intel: job state not matched (stdout follows)
JobID|State|ExitCode|NodeList
22423095_1|RUNNING|0:0|nid0[2544-2545]
22423095_1.extern|RUNNING|0:0|nid0[2544-2545]
22423095_0|RUNNING|0:0|nid0[2517-2518]
22423095_0.extern|RUNNING|0:0|nid0[2517-2518]
```

and

```
[2019-06-20T12:19:04] debug: slurm_job_arrays on cori:knl using PrgEnv-intel: entering stage: poll
[2019-06-20T12:19:04] debug: slurm_job_arrays on cori:knl using PrgEnv-intel: executing OS command: sacct -S 2019-06-20 -P -j 22423095 -o jobid,state,exitcode,nodelist
[2019-06-20T12:19:04] debug: slurm_job_arrays on cori:knl using PrgEnv-intel: job state not matched (stdout follows)
JobID|State|ExitCode|NodeList
22423095_1|COMPLETED|0:0|nid0[2544-2545]
22423095_1.batch|COMPLETED|0:0|nid02544
22423095_1.extern|COMPLETED|0:0|nid0[2544-2545]
22423095_1.0|COMPLETED|0:0|nid0[2544-2545]
22423095_0|COMPLETED|0:0|nid0[2517-2518]
22423095_0.batch|COMPLETED|0:0|nid02517
22423095_0.extern|COMPLETED|0:0|nid0[2517-2518]
22423095_0.0|COMPLETED|0:0|nid0[2517-2518]
```

I wonder if ReFrame gets confused by the output having the form `<job_id>_<array_task_num>` as opposed to just `job_id`?

### PR DESCRIPTION
**Pull request by teojgo**
* Add logging info when an array job is detected and during file merging.

Related to #840 
Fixes #839

### CODE REVIEW

**Comment by bcfriesen** [comment]
Hi @teojgo,

thanks for working on this - unfortunately it still does not work for me. I noticed that the directory from which I invoke ReFrame to run the job arrays test now has a `.out` and `.err` file, but both are blank. The `.out_0` and `.out_1` and `.err_0` and `.err_1` files are all still in the stage dir.

**Comment by teojgo** [comment]
@bcfriesen this is strange. Can you post the log lines mentioning the merging of files?

**Comment by bcfriesen** [comment]
Hi @teojgo,

hmm, I see no logs discussing merging files. I am running on commit cdd45011 and using `reframe -v`. Should I be doing something else?

**Comment by teojgo** [comment]
Hello @bcfriesen,

Please checkout to the branch of this PR and run again. Then the reframe.log should contain information regarding the merging of files.

**Comment by bcfriesen** [comment]
Hi @teojgo,

ahh now it all works. Sorry I think I was one commit behind this PR. Everything works now - the merging message is in the log, and the job arrays test passes. Thanks!

**Comment by teojgo** [comment]
@bcfriesen thank you for the feedback. We are going to review now and merge the PR.

**Comment by vkarak** [comment]
@jenkins-cscs retry all

**Pull request merged**
