### PR TITLE
[test] Update tf2 Horovod check

### PR DESCRIPTION
**Pull request by henrique**

### CODE REVIEW

**Comment by teojgo** [comment]
Ok to test

**Comment by teojgo** [comment]
@jenkins-cscs retry all

**Comment by henrique** [comment]
@jenkins-cscs retry daint

**Comment by henrique** [comment]
@jenkins-cscs retry daint

**Comment by henrique** [comment]
@jenkins-cscs retry daint

**Comment by henrique** [comment]
@jenkins-cscs retry daint

**Comment by henrique** [comment]
@jenkins-cscs retry daint

**Comment by henrique** [comment]
can we merge this please?
thx

**Review by vkarak — APPROVED** [review]
lgtm

**Pull request merged**
