### PR TITLE
[bugfix] Fix unittests for module collections

### PR DESCRIPTION
**Pull request by teojgo**
* Monkeypatch the `LMOD_SYSTEM_NAME` so that the temporary collection
  name does not depend on it.

* Add ci configuration for eiger/pilatus.

### CODE REVIEW

**Review by jjotero — APPROVED** [review]
lgtm

**Comment by teojgo** [comment]
@jenkins-cscs retry eiger

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by teojgo** [comment]
@jenkins-cscs retry eiger

**Pull request merged**
