### PR TITLE
[test] Enable performance reporting in the flexible alltoall OSU benchmark

### PR DESCRIPTION
**Pull request by ajocksch**

### CODE REVIEW

**Comment by ajocksch** [comment]
Shall I merge the "alltoall" check with the "Flexible alltoall" check?

**Comment by vkarak** [comment]
@ajocksch For a PR to be merged, at least one approving review is needed. I'll have a look at it today.

**Comment by vkarak** [comment]
@ajocksch Can you please address my comments here, so that we can merge it?

**Comment by vkarak** [comment]
Regarding the CI: opened JIRA issue for the failing tests on Kesch and the failure on Dom is due to lack of resources. Merging.

**Pull request merged**
