### PR TITLE
Fix failure of the asynchronous execution policy's unit tests

### PR DESCRIPTION
**Pull request by vkarak**

### CODE REVIEW

**Comment by teojgo** [comment]
In my local computer it works fine. But it is still failing in Travis and the error is `AssertionError: 4 != 2` instead of `AssertionError: 4 != 3`.

**Comment by vkarak** [comment]
Do you see the `4 != 3` error? In which test? Because a see another error in another test:

```
FAIL: test_kbd_interrupt_in_wait_with_concurrency (unittests.test_policies.TestAsynchronousExecutionPolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/eth-cscs/reframe/unittests/test_policies.py", line 299, in test_kbd_interrupt_in_wait_with_concurrency
    self._run_checks(checks, 4)
  File "/home/travis/build/eth-cscs/reframe/unittests/test_policies.py", line 289, in _run_checks
    self.assertEqual(4, self.runner.stats.num_failures())
AssertionError: 4 != 2
----------------------------------------------------------------------
```

**Comment by vkarak** [comment]
I'm gonna fix this test, too. The fix is the same as for the other one failing.

**Comment by teojgo** [comment]
Before the fix when the error was thrown, the assertion was `4 !=3`.

**Comment by vkarak** [comment]
@teojgo It's crucial to see which test was failing exactly, because until now there three different types of failure!

**Comment by teojgo** [comment]
I am referring to the failures like the ones in https://github.com/eth-cscs/reframe/pull/143. This PR does not contain the fix.

**Comment by vkarak** [comment]
@teojgo Wait a sec, #143 does not contain the fix apparently, cos this one is not merged with the master. So you will be getting the `4 != 3` error, which btw is different from the first similar error, that #135 fixed. Check the last comment on #78 to see the difference. Now in *this* PR there is another unit test failing (because of the same reason that the async unit tests with limited concurrency were failing).

**Comment by teojgo** [comment]
Yes I see, indeed this is another test that is failing.

**Comment by teojgo** [comment]
@jenkins-cscs retry dom

**Comment by vkarak** [comment]
I've rerun the Travis CI several times and the fix seems to work. @omlins @teojgo Could you guys, approve this PR (if you don't have any other objections, of course).

**Comment by teojgo** [comment]
I tested many times locally and it works fine.

**Pull request merged**
