### PR TITLE
[test] Fix minor bug in sanity pattern for GPU burn test

### PR DESCRIPTION
**Pull request by akesandgren**
The perf value may have two space in front of it if <1000.
There is never a space between the GPU number and the (OK) value.

### CODE REVIEW

**Comment by vkarak** [comment]
ok to test

**Review by jjotero — APPROVED** [review]
lgtm

**Review by vkarak — APPROVED** [review]
lgtm too.

**Comment by vkarak** [comment]
Thanks @akesandgren!

**Pull request merged**
