### PR TITLE
[test] Cleanup cray_cdt_version in TensorFlow test

### PR DESCRIPTION
**Pull request by henrique**

### CODE REVIEW

**Comment by henrique** [comment]
@jenkins-cscs retry daint

**Review by vkarak — APPROVED** [review]
lgtm

**Comment by vkarak** [comment]
@jenkins-cscs retry daint

**Review by teojgo — APPROVED** [review]
The tf version might also vary in the feature, but for the moment it's fine.

**Comment by henrique** [comment]
> The tf version might also vary in the feature, but for the moment it's fine.

Yeah, we'll have tf2.4 in dom soon
Not sure how we'll solve that then. We could use the default module but there's also the pytorch horovod...

**Pull request merged**
