### PR TITLE
[misc] Add copyright year 2021 to all src files

### LINKED ISSUE #1684: Update copyright year to 2021 in all files

### PR DESCRIPTION
**Pull request by teojgo**
Fixes #1684

### CODE REVIEW

**Comment by victorusu** [comment]
The files changes "highlighted" by GitHub are not related to copyritght... I was mislead by that, because the removal of `imports` from python packages is not related... 😂

**Review by victorusu — APPROVED** [review]
`lgtm`

**Review by ekouts — CHANGES_REQUESTED** [review]
Lgtm in general, but I found some files with the old copyright date.
```
tutorials/basics/hello/src/hello.c
tutorials/basics/hello/src/hello.cpp
tutorials/basics/hellomp/src/hello_threads.cpp
tutorials/misc/makefiles/src/dotprod.cpp
```
And maybe we should also change `LICENSE` and `conf.py` unless you think they should be fixed in a different PR?

**Review by ekouts — APPROVED** [review]

**Review by vkarak — APPROVED** [review]
lgtm

**Comment by vkarak** [comment]
@jenkins-cscs retry none

**Pull request merged**
