### PR TITLE
[ci] Temporarily disable the params variable

### PR DESCRIPTION
**Pull request by victorusu**

### CODE REVIEW

**Comment by teojgo** [comment]
@victorusu why do you need this change?

**Comment by gppezzi** [comment]
@teojgo the params API was not working properly for a couple of days, CI was not running properly:
```
No machines were found. Aborting...
```
See for example [build #2247](https://jenkins.cscs.ch/blue/organizations/jenkins/ReframeCI/detail/ReframeCI/2247/pipeline)

**Comment by teojgo** [comment]
@gppezzi this is strange since the `params` was defined for that build. In any case I update all the related jenkins plugins. Let's see how it goes.

**Comment by gppezzi** [comment]
I also updated the plugins last week (twice actually) and it didn't help. Now it seems to be working again (CI build 2251 worked without merging this PR), so I assume that was a temporary glitch.

I think we can close this PR for the moment.

**Comment by teojgo** [comment]
I am closing this since everything seems to be working again.

**Pull request closed without merging**
