### PR TITLE
[WIP] Create the 'setup.py' file

### LINKED ISSUE #336: Package ReFrame and publish to PyPI
Information can be found in the following websites:

- https://packaging.python.org/
- http://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/index.html

### PR DESCRIPTION
**Pull request by teojgo**
Closes #336

### CODE REVIEW

**Comment by teojgo** [comment]
@vkarak @victorusu can you try cloning the branch and then running `pip install <your_path>`? Also, can you suggest the classifiers that would be suitable for Reframe from [pypi](https://pypi.org/classifiers/)

**Comment by vkarak** [comment]
@teojgo What's the status of this one?

**Comment by teojgo** [comment]
@vkarak put it to the upcoming sprint and I am going to address it.

**Comment by vkarak** [comment]
@teojgo I will close this PR and remove the branch, so as to clean-up the repo. You may redo it from your fork.

**Pull request closed without merging**
