### PR TITLE
[WIP] Try stages feature

### PR DESCRIPTION
**Pull request by teojgo**

### CODE REVIEW

**Comment by vkarak** [comment]
I don't know if this is exactly what we want. Ideally, we want a completely different entry in the checks list. So I don't think that this is a stage of a CI test.

**Comment by teojgo** [comment]
@jenkins-cscs retry nothing

**Comment by teojgo** [comment]
@vkarak I know what you want I am just trying some features that are still in `beta` stage for travis.

**Comment by vkarak** [comment]
@teojgo Can we close this PR?

**Pull request closed without merging**
