### PR TITLE
[bugfix] Back port Slurm fixes to ReFrame 2.17

### PR DESCRIPTION
**Pull request by vkarak**
Slurm was updated on Daint, so we need to back port some fixes of master to the 2.17 running on Daint. This PR back ports the following fixes: #835, #836, #837, #845.

### CODE REVIEW

**Comment by teojgo** [comment]
Maybe you can include also #923 fix into it.

**Comment by vkarak** [comment]
@teojgo If it's for Daint, sure.

**Comment by vkarak** [comment]
@jenkins-cscs retry kesch

**Comment by vkarak** [comment]
@jenkins-cscs retry none

**Pull request merged**
