### PR TITLE
[test] Fix CDO checks

### PR DESCRIPTION
**Pull request by omlins**
The CDO version installed on Daint/Dom is not the same as the one on Tsa/Arolla and they print a different message in case of success. This PR generalizes the sanity check to work with both CDO versions.

### CODE REVIEW

**Comment by vkarak** [comment]
@omlins Can you please put in the description the internal issues that this one fixes?

**Comment by omlins** [comment]
@jenkins-cscs retry tsa

**Comment by omlins** [comment]
@jenkins-cscs retry all

**Comment by omlins** [comment]
@jenkins-cscs retry all

**Comment by vkarak** [comment]
@jenkins-cscs retry none

**Pull request merged**
