### PR TITLE
[feat] Delay the setup of performance logging, so that `perf_patterns` can be defined after the test construction

### LINKED ISSUE #1376: perflog is missing when perf_patterns is defined inside a decorator function
If you look at the code in [UES-911](https://github.com/jgphpc/reframe/tree/UES-911),

> reframe -C ./jg.py --system dom:login -r -p PrgEnv-gnu -c ko.py

will not generate `perflogs/dom/login/ExampleRunLoggingTest.log` while ok.py does.

Is this an issue with jg.py ?

### PR DESCRIPTION
**Pull request by ekouts**
Fixes #1376 .
I tested it with @jgphpc 's example and it works.

### CODE REVIEW

**Comment by ekouts** [comment]
@jenkins-cscs retry all

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by ekouts** [comment]
@jenkins-cscs daint

**Comment by ekouts** [comment]
@jenkins-cscs daint

**Review by vkarak — APPROVED** [review]
lgtm

**Pull request merged**
