### PR TITLE
[test] Adapt GROMACS test to Eiger

### PR DESCRIPTION
**Pull request by lucamar**
GROMACS small and large check on Eiger: reference values are tentative as there might be room for improvement.

### CODE REVIEW

**Comment by lucamar** [comment]
@jenkins-cscs retry eiger

**Comment by vkarak** [comment]
Hi @lucamar, can you remove the unused imports as indicated by this check? https://github.com/eth-cscs/reframe/pull/1657/checks?check_run_id=1551861788

**Comment by lucamar** [comment]
@jenkins-cscs retry eiger

**Comment by lucamar** [comment]
I will update the pull request once #1658 is merged to fix the issue with parallel unittests on Eiger.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by lucamar** [comment]
@jenkins-cscs retry eiger

**Review by vkarak — APPROVED** [review]
lgtm, too

**Comment by lucamar** [comment]
@jenkins-cscs retry eiger

**Pull request merged**
