### PR TITLE
[test] Port GPUBURN check to Tiger

### PR DESCRIPTION
**Pull request by jgphpc**
Will fix UES-567

### CODE REVIEW

**Comment by jgphpc** [comment]
@jenkins-cscs retry kesch

**Comment by jgphpc** [comment]
```
FAILURE INFO for GpuBurnTest 
  * System partition: kesch:cn
  * Environment: PrgEnv-gnu
  * Stage directory: /scratch-shared/meteoswiss/scratch/jenscscs/reframe-ci-kesch-e05c9c0-2575/stage/kesch/cn/PrgEnv-gnu/GpuBurnTest
  * Job type: batch job (id=None)
  * Maintainers: ['AJ', 'VK', 'TM']
  * Failing phase: compile
  * Reason: environ error: could not load module 'craype-accel-nvidia35' correctly: command 'modulecmd python load craype-accel-nvidia35' failed with exit code 0:
=== STDOUT ===
os.environ['LOADEDMODULES'] = 'craype-network-infiniband:craype-haswell:slurm/17.11:bzip2/.1.0.6:zlib/.1.2.11:ncurses/.6.0:python-bare/.3.6.8:reframe/2.19:cray_PE/17.06:gnu_PE/17.02:pgi_PE/18.5:PE/17.06:gcccore/.5.4.0:binutils/.2.26-gcccore-5.4.0:gcc/5.4.0-2.26:cudatoolkit/8.0.61:mvapich2gdr_gnu/2.2_cuda_8.0:mvapich2/2.2-5.4.0-2.27_cuda_8.0_gdr:gmvapich2/17.02_cuda_8.0_gdr:cray-libsci_acc/18.10.1:craype-accel-nvidia35'
```

**Comment by jgphpc** [comment]
@ajocksch @teojgo  is there an issue with the setup on kesch ?

**Comment by vkarak** [comment]
Opened UES-588 for the failure on Kesch. Merging.

**Pull request merged**
