### PR TITLE
[test] Include Eiger in OSU benchmarks

### PR DESCRIPTION
**Pull request by rsarm**
Addresses UES-1429

### CODE REVIEW

**Review by lucamar — APPROVED** [review]
Thanks @rsarm

**Review by vkarak — APPROVED** [review]

**Comment by vkarak** [comment]
@rsarm The tests are failing on Eiger. Can you have a look?

**Comment by rsarm** [comment]
Didn't do anything. Empty output and only this on the err:
```
slurmstepd: error: *** JOB 30367 ON nid001330 CANCELLED AT 2021-02-17T09:42:38 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 30367 STEPD TERMINATED ON nid001330 AT 2021-02-17T09:46:08 DUE TO JOB NOT ENDING WITH SIGNALS ***
```
I will retest again.

**Comment by rsarm** [comment]
@jenkins-cscs retry eiger

**Pull request merged**
