### PR TITLE
[test] Update Intel VTune test

### PR DESCRIPTION
**Pull request by jgphpc**
Will fix [485](https://jira.cscs.ch/browse/UES-485)

### CODE REVIEW

**Comment by jgphpc** [comment]
```

=================================== FAILURES ===================================
___________________________ TestSlurmJob.test_cancel ___________________________

self = <unittests.test_schedulers.TestSlurmJob testMethod=test_cancel>

    def test_cancel(self):
>       super().test_cancel()

unittests/test_schedulers.py:381: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
reframe/core/runtime.py:321: in _fn
    ret = fn(*args, **kwargs)
unittests/test_schedulers.py:143: in test_cancel
    self.assertLess(t_job.total_seconds(), 30)
E   AssertionError: 44.797643 not less than 30
============== 1 failed, 557 passed, 22 skipped in 561.43 seconds ==============
===================================
Running unit tests with PBS backend
===================================
```

**Comment by jgphpc** [comment]
@jenkins-cscs retry this please

**Comment by jgphpc** [comment]
[unittest](https://jenkins.cscs.ch/blue/organizations/jenkins/ReframeCI/detail/ReframeCI/2241/pipeline/19) seems to have failed with:

```
Setting status of 6eab36a4d5e412058e064d2ab2250eb51e36a063 to FAILURE 
with url https://jenkins.cscs.ch/job/ReframeCI/2241/ and message: ' '
```

@jenkins-cscs retry this please

**Comment by jgphpc** [comment]
@jenkins-cscs retry this please

**Comment by jgphpc** [comment]
same [issue:](https://jenkins.cscs.ch/blue/organizations/jenkins/ReframeCI/detail/ReframeCI/2242/pipeline/)

**Comment by jgphpc** [comment]
@jenkins-cscs retry this please

**Comment by jgphpc** [comment]
https://jenkins.cscs.ch/blue/organizations/jenkins/ReframeCI/detail/ReframeCI/2244/pipeline/19

**Comment by jgphpc** [comment]
@jenkins-cscs retry this please

**Comment by victorusu** [comment]
@jenkins-cscs retry this please

**Comment by victorusu** [comment]
Upon request, I am overwriting the CI failure. I will merge this test.

**Pull request merged**
