### PR TITLE
clean up and extend mpi+openacc test to work with n tasks

### PR DESCRIPTION
**Pull request by lxavier**
I only changed the the src file, the python script may need to be adapted since I added a ifdef, for Crar the -eZ option should be added.

I have only tested with Cray on Kesch

Addresses #247.

### CODE REVIEW

**Comment by vkarak** [comment]
@jenkins-cscs retry all

**Comment by lxavier** [comment]
yes unless the python compiler flags need to be adapted because of the ifdef (but I don't know where to edit)

**Comment by vkarak** [comment]
@lxavier This question was automatic from Jenkins. I've triggered the build also on our machines. My question though is now, do we need to adapt the corresponding ReFrame test as well?

**Comment by lxavier** [comment]
@vkarak yes please, the test code is ready from my side

**Comment by lxavier** [comment]
How should we proceed with the new codes that we want to add, should the responsible person add then in cscs-checks/prgenv/src in branches, or send you the code sample ? Some of then will contain multiple files (e.g. openacc+cuda).

**Comment by vkarak** [comment]
@lxavier I've replied to you by email.

**Comment by vkarak** [comment]
@lxavier I am about to merge this and then we will start working on updating the corresponding ReFrame test. What we are missing is how you run it?

**Comment by lxavier** [comment]
nothing special I would start to run it on one node (e.g. 8 GPUs on Kesch) just did srun -n 8
The important thing is to load the module that we use. Since our new module generator is not yet ready you could use the module file on /project  /project/c14/install/kesch/cosmo5/modules_fortran_gpu_double.env

**Comment by vkarak** [comment]
Thanks @lxavier

**Comment by lxavier** [comment]
true, I just wanted to implement some easy test where I could verify if ok or not on any number of proc. 
I suggest to start with that for now, but if you want to change it fine for me, you just need to exchange message that you can verify.

**Pull request merged**
