### PR TITLE
[test] Enable IOR test on Daint

### PR DESCRIPTION
**Pull request by GiuseppeLoRe**

### CODE REVIEW

**Comment by teojgo** [comment]
ok to test

**Comment by GiuseppeLoRe** [comment]
Without the line
super().__init__() in IorCheck.__init__ 
I get this error 

AttributeError: IorWriteCheck object has no attribute '_current_partition'

**Comment by teojgo** [comment]
@GiuseppeLoRe You can remove the `super().__init()__` only in the base class that inherits the `rfm.RegressionTest`.

**Comment by vkarak** [comment]
@teojgo Perhaps @GiuseppeLoRe uses an older version of reframe. This feature was introduced in 2.18.

**Comment by GiuseppeLoRe** [comment]
I am using the daint default one, 2.17.1

**Comment by GiuseppeLoRe** [comment]
Should I test with 2.18 or 2.19?

**Comment by vkarak** [comment]
So then keep the call to `__init__()`, because we are going to use this test on Daint immediately.

**Comment by GiuseppeLoRe** [comment]
ok

**Comment by GiuseppeLoRe** [comment]
Now that I do the tests twice, one for the gpu partition and then again for the mc one, I get the caching effect on the second test.
Is there a variable "current_partition" I can use to differentiate the output files?

**Comment by vkarak** [comment]
@GiuseppeLoRe Yes, you can. This information is available in the  `setup()` method, so you will have to override this in your test. Check the example [here](https://reframe-hpc.readthedocs.io/en/v2.17/tutorial.html#customizing-the-compilation-phase) on how to do this. The link refers to reframe 2.17, which is the version you are using.

**Comment by GiuseppeLoRe** [comment]
@vkarak thanks for the link, but at least for me the example is not very clear.

**Comment by vkarak** [comment]
@GiuseppeLoRe What do you want to do based on the current programming environment?

**Comment by GiuseppeLoRe** [comment]
@vkarak I would like the partition mane (mc or gpu) to build the ior output file name. And thought that I could use something like https://reframe-hpc.readthedocs.io/en/stable/reference.html#reframe.core.pipeline.RegressionTest.current_partition....

**Comment by vkarak** [comment]
Yes, you can do that, but `current_partition` is only defined after the setup stage of the pipeline. You can do it as follows:

```python
    def setup(self, partition, environ, **job_opts):
        super().setup(partition, environ, **job_opts)
        if self.current_partition.name == 'gpu':
            self.executable_opts = [...]
        else:
            self.executable_opts = [...]
```

You may also write this as follows:

```python
    def setup(self, partition, environ, **job_opts):
        if partition.name == 'gpu':
            self.executable_opts = [...]
        else:
            self.executable_opts = [...]

        super().setup(partition, environ, **job_opts)
```

And from version 2.20 (or even from the current master), you will be able to write this as follows:

```python
    @rfm.run_after('setup')
    def choose_your_function_name(self):
        if self.current_partition.name == 'gpu':
            self.executable_opts = [...]
        else:
            self.executable_opts = [...]    
```

**Comment by GiuseppeLoRe** [comment]
Tested on Daint.

**Comment by vkarak** [comment]
@GiuseppeLoRe The test is MPI-based, so ignore my comment. I am merging this.

**Pull request merged**
