### PR TITLE
[test] Add `dom:mc` as valid system to `IntelRooflineAdvisorTest`

### PR DESCRIPTION
**Pull request by jgphpc**
Will fix UES-418

### CODE REVIEW

**Comment by jgphpc** [comment]
@jenkins-cscs retry all

**Comment by jgphpc** [comment]
It passed:

```
[       OK ] IntelRooflineAdvisorTest_100000_597843_G3_AOS_VECTOR on dom:mc using PrgEnv-intel
[       OK ] IntelRooflineAdvisorTest_100000_597843_G3_AOS_SCALAR on dom:mc using PrgEnv-intel
[       OK ] IntelRooflineAdvisorTest_100000_597843_G3_SOA_SCALAR on dom:mc using PrgEnv-intel
[       OK ] IntelRooflineAdvisorTest_100000_597843_G3_SOA_VECTOR on dom:mc using PrgEnv-intel
```

**Comment by teojgo** [comment]
@jenkins-cscs retry all

**Comment by vkarak** [comment]
@jenkins-cscs retry dom

**Pull request merged**
